version: "2"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/work
      - ruby2.3-bundle-cache:/usr/local/bundle
    working_dir: /work

volumes:
  ruby2.3-bundle-cache:
    external: true
