#! /bin/bash -e

cd $(dirname $0)/..

REPOSITORY=cowbell/tagfish
VERSION=$(cat lib/tagfish/version.rb | grep VERSION | cut -d'"' -f2)

# Build the image
docker build -t ${REPOSITORY}:latest .

# Release the image
docker push ${REPOSITORY}:latest
docker tag ${REPOSITORY}:latest ${REPOSITORY}:${VERSION}
docker push ${REPOSITORY}:latest
