#! /bin/bash -e

cd $(dirname $0)/..

REPOSITORY=cowbell/tagfish
VERSION=$(cat lib/tagfish/version.rb | grep VERSION | cut -d'"' -f2)

# Ensure we have no local changes
git diff HEAD --exit-code

auto/release-gem
auto/release-docker-image
